name: pizza_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' 

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter : ^10.12.0
  firebase_core: ^2.27.0  
  firebase_auth: ^4.19.0 
  cloud_firestore: ^4.17.0 
  firebase_storage: ^11.7.7

  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.6

  user_repository:
    path: packages/user_repository
  pizza_repository:
    path: packages/pizza_repository

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 

flutter:
  uses-material-design: true
  
  assets:
    - assets/